title: Rudolf Metzler
subtitle: M.Sc. Geomatics Engineering
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: me.png
disqus_shortname: rmetzler  #for comments using disqus
author: Rudolf Metzler
author_bio: "
Kernaussage: Motivierter abitionierter Absolvent<br>
Recently graduated master student from Hamburg, Germany. 
I made this website to show my motivation about programming and its application.
As an engineer, I see software tools as an important key to solve problems.
"
author_email: "contact@rmetzler.com"
author_location: Hamburg, Germany
author_website_url: "https://rmetzler.com"

# social links
#twitter_username: yourusername
github_username:  inecho
gitlab_username:  inecho
linkedin_username: rudolf-metzler
soundcloud_username: rstation
mixcloud_username: rstation

collections:
  - jobs
  - edu
  - skills