# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: ''
description: 'Comming soon..'

# Images
avatar: 'avatar.gif'
background: 'background.gif'
favicon: 'favicon.ico'

# Online profiles
#dribbble: 'mydribbble'
facebook: 'myfacebook'
twitter: 'mytwitter'
#linkedin: 'mylinkedin'
instagram: 'myinsta'
#pinterest: 'mypinterest'
youtube: 'myyoutube'
github-user: 'mygithub'
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#rubygems: ''
#medium:  ''
tumblr: 'mytumblr'
weibo: 'myweibo'
vk: 'myvk'
blog_url: 'myblog.blog.com'
email: 'hello@example.com'
messenger: 'myfbchat'

social-links-order: [github-user, facebook, twitter, instagram, tumblr, pinterest, linkedin, youtube, vk, weibo, dribbble, messenger, blog_url, email]

# Advanced settings
plugins:
  - jekyll-remote-theme

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__

  - name: github-user
    url-pattern: github.com/inecho
    icon-class: fab fa-2x fa-github

  - name: gitlab-user
    url-pattern: gitlab.com/inecho
    icon-class: fab fa-2x fa-gitlab

  - name: blog_url
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-tags

  - name: email
    url-scheme: 'mailto:'
    url-pattern: 'contact@rmetzler.com'
    icon-class: fas fa-2x fa-envelope
